
// This file has been generated by the GUI designer. Do not modify.
namespace Haxe_Binding
{
	public partial class HaxeOptionsWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Haxe_Binding.HaxeOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Haxe_Binding.HaxeOptionsWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
